/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/blog': RouteRecordInfo<'/admin/blog', '/admin/blog', Record<never, never>, Record<never, never>>,
    '/admin/faq': RouteRecordInfo<'/admin/faq', '/admin/faq', Record<never, never>, Record<never, never>>,
    '/admin/login': RouteRecordInfo<'/admin/login', '/admin/login', Record<never, never>, Record<never, never>>,
    '/admin/modules': RouteRecordInfo<'/admin/modules', '/admin/modules', Record<never, never>, Record<never, never>>,
    '/admin/projects': RouteRecordInfo<'/admin/projects', '/admin/projects', Record<never, never>, Record<never, never>>,
    '/article/[id]': RouteRecordInfo<'/article/[id]', '/article/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/courseIntroduction': RouteRecordInfo<'/courseIntroduction', '/courseIntroduction', Record<never, never>, Record<never, never>>,
    '/howToSignUp': RouteRecordInfo<'/howToSignUp', '/howToSignUp', Record<never, never>, Record<never, never>>,
    '/otherInfo': RouteRecordInfo<'/otherInfo', '/otherInfo', Record<never, never>, Record<never, never>>,
  }
}
